### ISSUE TITLE
[BUG]: Footer text wrapping misaligned

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The address is being warped down at the wrong spots in the footer

![image](https://github.com/rbjks/rbjks.github.io/assets/43912470/91ea0994-ca51-4697-876b-78ab9bfef91f)

### Expected Behavior

The text be split over lines such that no word is truncated or divided over two lines.
If this modification will lead to changes in the desktop view as well, please convey so in the PR.

### Steps To Reproduce

1. Open website in mobile view
2. Scroll to the footer

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by mohit-bhandari45** [comment]
I want to work on this

**Comment by Bashamega** [comment]
Hello:)
I would love to work on this.
Please assign it to me
I will add this to the css to fix it:
```
white-space:pre-wrap;
word-break:break-word;
```
Preview:
![image](https://github.com/rbjks/rbjks.github.io/assets/110662505/4a4681a9-36e6-4b2a-b6ea-3cccc8f94ab6)

**Comment by adityaraute** [comment]
I'd like to see the preview before assigning, if that's okay

**Comment by Bashamega** [comment]
For the logo i have fixed it, but the text wrapping can't be fixed because there are many mobiles with different sizes, but we can add a js code that checks if it is a mobile to add a `br` tag before district, which will make the district on a new line. for the hyphon spaces we can easily get rid of it by just deleting the spaces
This is the logo:
![image](https://github.com/rbjks/rbjks.github.io/assets/110662505/07154528-1ba3-469d-a01c-b060d1083271)

**Comment by RohanRam** [comment]
Hy @adityaraute Is this still on?

**Comment by adityaraute** [comment]
It is but first I'd like an update from you on #143

**Comment by caiodutra08** [comment]
Can I take this?

**Comment by caiodutra08** [comment]
Already finished im my local repo what is being asked for, just lmk if I can take this.

**Comment by caiodutra08** [comment]
Also fixed aswell a hamburguer bug that was occurring in every media width.
