### ISSUE TITLE
Change Prettier workflow options to format all files

### ISSUE THREAD

**Issue by adityaraute** [rbjks/rbjks.github.io#65]
**Describe the bug**
Currently Prettier only formats `js` files with the workflow `prettier.yml`

**Expected behavior**
The workflow should format all code files present in the repository

**Additional context**
Investigate the `parameters` [here](https://github.com/creyD/prettier_action#parameters)
We can modify the options such that the workflow formats all files

**Comment by b-mendoza** [comment]
Hey @adityaraute 👋

Would you be open to changing how formatting is applied to the code?

I believe it would be more beneficial to shift towards a global config file at the root instead of using a GitHub action to format the code, so new and existing contributors will have the same code formatting settings

Additionally, you could integrate the formatting process into a pre-commit hook so you can guarantee that the code will be formatted before a commit is made

Let me know what you think. I'll be happy to create a PR for this 😄

**Comment by agriyakhetarpal** [comment]
A global config file or a pre-commit hook are both great ways to handle formatting. I'll assign you to the issue, @b-mendoza – in addition, if we can have https://pre-commit.ci/ running for the repository soon that will be great (but I think @adityaraute will have to configure it)

**Comment by b-mendoza** [comment]
Sounds good!

Are there any setting for Prettier you'd like me to use?

If not, I'll use most of the default settings, with the exception of the following:

```yml
singleQuote: true
```

Keep in mind that as well a `package.json` file and a package manager lock file will be added. To keep it simple, I'll use npm

If you'd like me to use any other package manager or have any preferred Prettier settings, please let me know 🫡
